### ISSUE TITLE
 resnet50+cbam pre-training weight

### ISSUE THREAD

**Issue by mei123456789** [Ugenteraan/ResNet-50-CBAM-PyTorch#1]
Is there a resnet50+cbam pre-training weight? I need your help. Thank you

**Comment by mei123456789** [comment]
Could you please provide the weights you have trained? Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ugenteraan/ResNet-50-CBAM-PyTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月18日(星期一) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ugenteraan/ResNet-50-CBAM-PyTorch]  resnet50+cbam pre-training weight (Issue #1)





 
Sorry, I trained the model in my repo without using any pre-trained weight.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ugenteraan** [comment]
@mei123456789 please refer to the README for the training weights. Thank you.
